Completed basic functionality
Beach-Plum-Partiers/PLUMBERSFEC pull request #28
Opened 2023-05-15 04:49 UTC by Dmigdol

2023-05-15 17:52 UTC, cesargua requested changes
Take another look at index.js

2023-05-15 17:52 UTC, cesargua commented on server/index.js
> +<<<<<<< Updated upstream
get rid of this part please, this will break the code

2023-05-15 17:52 UTC, cesargua commented on server/index.js
> +>>>>>>> Stashed changes
And here

2023-05-15 17:52 UTC, cesargua requested changes
Take another look at index.js

2023-05-15 21:16 UTC, cesargua approved these changes

2023-05-15 21:23 UTC, Chugale approved these changes
should try and avoid using px if possible

2023-05-15 22:01 UTC, merged

2023-05-16 18:16 UTC, cesargua commented on client/src/components/questions_and_answers/Answers.jsx
> +      .catch((err) => {
Good job on error catching. Very container safe!

2023-05-16 18:16 UTC, cesargua commented on client/src/components/questions_and_answers/Modal.jsx
> +  const resetStates = () => {
I like how you used a helper function on resetting states, Very smart idea.

2023-05-16 18:16 UTC, cesargua commented on client/src/components/questions_and_answers/Search.jsx
> +      setFilter(questions.filter((question) => question.question_body.match(searchInput)));
Although this was a good one liner, you could split this one up to lessen complexity and clarity.